# run: docker-compose up -d
# verbose mode: docker-compose --verbose up
# build images: docker-compose build --no-cache

version: "3.3"
   
services:
  chrome:
    tty: true
    image: hpg_chrome_image
    container_name: hpg_chrome_container

    user: apps
    privileged: true

    # volumes:
    #   - ./:/hpg_base
    environment:
      - VNC_SERVER_PASSWORD=hpg_vnc_pass
    ports:
      - 5900:5900

    build:
      context: ./ 
      dockerfile: ./chrome.Dockerfile

    # restart: always
    # command: ./docker_chrome_startup.sh 


  crawler:
    tty: true
    restart: always
    container_name: hpg_crawler_container
    build: 
      context: ./../ 
      dockerfile: ./hpg_crawler/crawler.Dockerfile
    command: python hpg_crawler/driver.py 1
    volumes:
      - ./../:/hpg_base
    depends_on:
      - chrome

